name: flutter_app2
description: Another Flutter application.

dependencies:
  xml: "^3.0.0"
  meta: '>=1.1.0 <2.0.0'
  redux: ^3.0.0
  flutter_redux: ^0.5.0
  path_provider: "^0.4.0"
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
   - resources/lessons/lesson1

