const String lesson55= '''abad=a century
benar-benar=truly, really
benteng=a fort, a fortress
beragama=to be a follower of such-and-such a religion
berakhir=to come to an end, to finish, to end
berperang=to go to war, to wage war, to fight a war
budak=a slave
diberi=to be given something
dibunuh=to be murdered
didirikan=to be established, to be set up, to be founded
diganti=to be replaced
dikalahkan=to be defeated, to be beaten
dikembalikan=to be returned, to be taken back, to be given back
dikenal=to be recognised (as), to be acknowledged (as), to be known (as)
dinamakan=to be given the name ...
dipimpin=to be led, to be under the leadership of
dirusak=to be trashed, to be destroyed, to be deliberately ruined
diserang=to be attacked
ditarik=to be pulled, to be tugged, to be hauled
diumumkan=to be announced, to be made public
ibukota=the capital, a capital city
izin=permission, a permit
jatuh=to fall
jelas=clear, clearly visible, clearly understood
kemerdekaan=independence (especially the independence of a country/nation)
kerjaan=a kingdom
kuda=a horse
memimpin=to lead (someone or something, especially an organisation)
miskin=poor, poverty stricken
nasionalis=nationalist
perang=a war, war
perusahaan=a business company, a corporation, a firm
proklamasi=proclamation
raja=a king
sehat=in good health, healthy
takut=to be afraid, to be scared
tangan=a hand, an arm
tebu=sugar cane
tembakau=tobacco
terjadi=to happen
trem=a tram
usaha=an enterprise (especially a business enterprise), an effort
profesor=a professor, Professor so-and-so
sekalian=all (rather formal and literary)
penduduk=the population, the people who live in a certain place, the inhabitants of...
pemandu wisata=a tour guide
tanah=earth, ground, soil
''';