const String lesson26= '''bangun = to get up
berangkat = to leave, depart
berita = news
berpakaian = to get dressed
bersisir = to comb your hair
filem = film
gosok gigi = to brush your teeth
kepada = to (a person)
latihan = an exercise (eg in a textbook)
majalah = magazine
melihat = to look, to see
membaca = to read
membeli = to buy something
membersihkan = to clean something
mencari = to look for, to seek
mencuci = to wash something
mendengarkan = to listen to something
mengambil = to fetch something
menonton = to watch something
menulis = to write something
pakaian = clothes
olahraga = sport
piring = a plate, the dishes
sebelum = before
sesudah = after
surat = a letter
surat kabar = a newspaper
untuk = in order to
lalu = then
kemudian = then
pemandangan = a view, scenery
sendiri = alone
''';