const String lesson41= '''akuntan=an accountant
akuntansi=accountancy
dokter=a (medical) doctor
dokter gigi=a dentist
dosen=a university lecturer
efisien=efficient
gigi=a tooth, teeth
ibu rumah tangga=a housewife
insinyur=an engineer
sepak bola=football (soccer)
tukang listrik=an electrician
montir=a mechanic
jenis=a type, a category, a class of something, a species of something
karyawan=an employee, a member of the workstaff (especially a junior member)
mahasiswa=a university student
marah=angry
mengetik=to type
mesin tik=a typewriter
negeri=state (adjective), pertaining to the state or to the government
pegawai=an office worker, a white collar employee
pekerjaan=work, employment, a job, an occupation
palayan=a waiter, waitress
pemain=a player
pengusaha=a businessman, businesswoman
petani=a farmer
polisi=a policeman, a policewoman
rajin=hard working, disciplined and dedicated (of a worker or student), conscientious
rumah tangga=a household (i.e. all the people who live under one roof)
sakit=ill, sick, to be hurting (when you are talking about a part of the body)
sekretaris=a secretary
sopir=a (paid) driver
tentara=a soldier (also: the army)
terima telopon=to answer the phone, to take a phone call
tukang masak=a cook
wartawan=a reporter, a journalist
tukang kayu=a carpenter, joiner
tukang=a skilled worker (especially one who works with this hands or by physical exertion)
seniman=artist
''';