const String lesson18= '''aduh=Oh!
berapa harga=how much is..? (price)
berbelanja=to go shopping
bercakap-cakap=to chat
botol=a bottle
bunga=a flower
dia=he, she
gambar=a picture
harga=the price of something
jam=a clock, a watch
jam berapa=what time?
jam tangan=a wristwatch
jam dinding=a wall clock
kompor=a stove
kursi=a chair
kursi malas=an easy chair
lemari=a cupboard
lemari pakaian=a wardrobe
lampu=a lamp
meja=a table
meja makan=a dining table
meja tulis=a writing table
mereka=they, their
pot bunga=a flower pot
radio=a radio
televisi=a television
tempat buku=a book shelf
tempat tidur=a bed
sedang=in the process of...
''';