const String lesson45= '''atas=upper
beratus-ratus=hundreds, hundreds of ...
beribu-ribu=thousands, thousands of ...
berpuluh-puluh=tens, tens of ...
berumur=to be so many years of age, to be such-and-such an age, to be ... years old
bisnis=business, commerce, a business
cara=a way, the way (to do something)
dasar=the foundations/basics; basic, elementary
dengan=with
di atas=above, on top of, overhead, over (the top of)
di bawah=below, underneath
elektronik=electronic
filsafat=philosophy
hampir=almost
hasil=a result, an outcome, output
hukum=law, a law
ilmu pengetahuan=science
jadi=so (in conversation when you are introducing a question or comment about something that has been mentioned)
kambing=a goat (also loosely: a sheep)
kedokteran=medicine (i.e. the practice of medicine or the science of medicine)
kerbau=a water buffalo
khusus=special, particular, specialised
listrik=electricity, electrical, electric
mata kuliah=a subject/course of study (at a unuiversity)
mata pelajaran=a subject of study (especially at a primary or secondary school)
memilih=to choose something, to elect someone
memperbaiki=to repair something
mesin=a machine, an engine
milik=property of ..., owned by ..., belonging to ...
pelajar=a student (especially a high school student)
pendidikan=education
pertama=first
pertanian=agriculture, farming
pompa=a pump
rusak=broken down, ruined, out of order, not working, not working properly
sampai=until, to arrive, to reach (a place), to get there
sejarah=history
sekolah dasar=a primary school, an elementary school, a grade school
sekolah menengah=a high school, secondary school
sekola menengah pertama=a junior high school
sekolah menengah umum=a senior high school, a senior general high school
selesai=finished (doing or making something)
setiap=each, every
sistem=a system
teknik=engineering
teknik kimia=chemical engineering
teknik elektro=electrical engineering
teknik sipil=civil engineering
teknik mesin=mechanical engineering
teknik pertanian=agricultural engineering
tentu saja=of course
tingkat=a level, a floor (in a multi-storey building)
umum=general, public
usaha tani=an agricultural enterprise, a farming business
waktu=when, at the time when (introducing a clause referring to a particular time in the past when something happened)
pada waktu itu=at that time
lulus=to pass (an exam)
oleh karena itu= for this/that reason, because of this/that
ternyata=it turned out that ..., contrary to what you might expect...
mungkin=maybe, possibly
terakhir=last, final
''';