const String lesson44= '''mengucapkan=to pronounce (a sound or word), to say/utter something
huruf=a letter (in the alphabet), a script, a writing system
abjad=the alphabet
tulisan=writing, a piece of writing
ejaan=spelling
bagaimana=how
ucapan=the pronunciation (of a word)
sekali lagi=once more
rakyat=the people (especially the ordinary people of a country or community)
terima kasih kembali=you're welcome (responding to someone's expression of thanks)
e=a
bay=b
chay=c
day=d
ay=e
ef=f
gay=g
h=h
ee=i
jay=j
ke=k
el=l
em=m
en=n
oh=o
pay=p
kee=q
er=r
es=s
tay=t
oo=u
fay=v
way=w
eks=x
yay=y
zet=z
''';